name: Build LVGL ESP32 Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: lv_micropython/ports/esp32

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.0

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y make ninja-build python3-pip cmake
        pip install virtualenv

    - name: Build firmware
      run: |
        . $IDF_PATH/export.sh
        make submodules
        make BOARD=ESP32_GENERIC_SPIRAM

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: esp32-firmware
        path: lv_micropython/ports/esp32/build/*.bin
